title: Rose's Art Diary
description: Soft pastel anime-inspired portfolio
baseurl: "/art-folio"
url: "https://danae-pan.github.io"

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor